### ISSUE TITLE
Limit users to one upvote per username for each game

### ISSUE THREAD

**Issue by thomasweaver627** [ndzamboni/bone-zone-vision-board#20]
Users are able to submit potentially unlimited upvotes for each game

Steps to reproduce current issue:
1. Open channel with active bot
2. Create new game if none are available
3. Select Upvote multiple times

![image](https://github.com/ndzamboni/bone-zone-vision-board/assets/105765011/4889b20d-1f30-4eac-be62-750a9745a18c)

**Comment by ndzamboni** [comment]
Thank you sir.

**Comment by ndzamboni** [comment]
done. thank you for the contribution thomas!
